### ISSUE TITLE
Failed to activate the open-sesame package

### ISSUE THREAD

**Issue by TimMoore** [stevenhauser/open-sesame#7]
I got this error immediately on startup after updating Atom from 0.194 to 0.196.

**Atom Version**: 0.196.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [open-sesame](https://github.com/stevenhauser/open-sesame) package, v0.3.0

### Stack Trace

Failed to activate the open-sesame package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
  at Object.module.exports.activate (/Users/tmoore/.atom/packages/open-sesame/lib/open-sesame.coffee:35:23)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:222:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:203:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:147:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:195:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:434:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:418:29
  at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
  at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:413:19)
  at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:394:46)
  at Atom.module.exports.Atom.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom.js:623:21)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:86:23)
  at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:38:7)

```

### Commands

```
     -0:00.1.0 editor:outdent-selected-rows (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "disabledPackages": [
      "outdoor-theme",
      "clipboard-history",
      "merge-conflicts",
      "atom-alignment",
      "compare-files",
      "git-log",
      "save-session",
      "linter-ruby",
      "enhanced-package-list",
      "linter-haml",
      "deprecation-cop",
      "recent-projects",
      "linter-coffeelint"
    ],
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ],
    "projectHome": "/Users/tmoore/Projects",
    "destroyEmptyPanes": false
  }
}
```

### Installed Packages

```coffee
# User
blackspace, v1.0.2
file-icons, v1.5.4
highlight-selected, v0.9.2
language-haml, v0.20.0
linter, v0.12.1
linter-jshint, v0.1.2
linter-rubocop, v0.2.3
minimap, v4.8.0
open-sesame, v0.3.0
revert-buffer, v0.5.0
ruby-block, v0.3.3
ruby-block-converter, v3.5.0
subword-navigation, v2.7.0
trailing-spaces, v0.2.5
wrap-lines, v0.2.0

# Dev
No dev packages
```

**Comment by stevenhauser** [comment]
Probably from API updates. I'll try to find time this weekend to fix. Thanks for the report.

**Comment by stevenhauser** [comment]
Whoops, didn't realize GitHub would autoclose this. @TimMoore let me know if #8 fixed this issue. Please reopen if it did not.

**Comment by TimMoore** [comment]
Thanks for the fix. I can't seem to reproduce the error anyway. It no longer happens when I relaunch Atom... only the first time right after updating.
